--- #YAML:1.0
name: CGI-Application-Plugin-TT
version: 0.03
author: Cees Hek <cees@crtconsulting.ca>
abstract: |-
  Plugin that adds Template Toolkit support to CGI::Application
license: perl
requires:
  CGI::Application: 3
  Template: 2.0
provides:
  CGI::Application::Plugin::TT:
    file: lib/CGI/Application/Plugin/TT.pm
    version: 0.03
generated_by: Module::Build version 0.25
